const portfolios = [
  // {
  //   id: 1,
  //   title: "movie website",
  //   category: "mern stack",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  // {
  //   id: 2,
  //   title: "dictinary app",
  //   category: "react",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  // {
  //   id: 3,
  //   title: "resume",
  //   category: "html/css/js",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  // {
  //   id: 4,
  //   title: "book store",
  //   category: "bootstrap",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  {
    id: 5,
    title: "moon",
    category: "css animation",
    image: "assets/portfolio/css-animation/animated-moon.png",
    webLink: "https://signal-fish.gitee.io/animated-moon/",
    sourceLink: "https://github.com/signal-fish/animated-moon",
  },
  {
    id: 6,
    title: "tea cup",
    category: "css animation",
    image: "assets/portfolio/css-animation/animated-tea-cup.png",
    webLink: "https://signal-fish.gitee.io/animated-tea-cup/",
    sourceLink: "https://github.com/signal-fish/animated-tea-cup",
  },
  {
    id: 6,
    title: "clock",
    category: "css animation",
    image: "assets/portfolio/css-animation/clock.png",
    webLink: "https://signal-fish.gitee.io/clock/",
    sourceLink: "https://github.com/signal-fish/clock",
  },
];

export default portfolios;
