const portfolios = [
  // {
  //   id: 1,
  //   title: "movie website",
  //   category: "mern stack",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  // {
  //   id: 2,
  //   title: "dictinary app",
  //   category: "react",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  // {
  //   id: 3,
  //   title: "resume",
  //   category: "html/css/js",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  // {
  //   id: 4,
  //   title: "book store",
  //   category: "bootstrap",
  //   image: "assets/portfolio/mern-stack/admin-dashboard.png",
  //   webLink: "",
  //   sourceLink: "",
  // },
  {
    id: 5,
    title: "moon",
    category: "css animation",
    image: "assets/portfolio/css-animation/animated-moon.png",
    webLink: "https://signal-fish.gitee.io/animated-moon/",
    sourceLink: "https://github.com/signal-fish/animated-moon",
  },
  {
    id: 6,
    title: "tea cup",
    category: "css animation",
    image: "assets/portfolio/css-animation/animated-tea-cup.png",
    webLink: "https://signal-fish.gitee.io/animated-tea-cup/",
    sourceLink: "https://github.com/signal-fish/animated-tea-cup",
  },
  {
    id: 7,
    title: "clock",
    category: "css animation",
    image: "assets/portfolio/css-animation/clock.png",
    webLink: "https://signal-fish.gitee.io/clock/",
    sourceLink: "https://github.com/signal-fish/clock",
  },
  {
    id: 8,
    title: "shining text",
    category: "css animation",
    image: "assets/portfolio/css-animation/shining-text.png",
    webLink: "https://signal-fish.gitee.io/shining-text/",
    sourceLink: "https://github.com/signal-fish/shining-text",
  },
  {
    id: 9,
    title: "birthday reminder",
    category: "react",
    image: "assets/portfolio/react/birthday-reminder.png",
    webLink: "https://signal-fish.gitee.io/birthday-reminder/",
    sourceLink: "https://github.com/signal-fish/birthday-reminder",
  },
  {
    id: 10,
    title: "loading",
    category: "css animation",
    image: "assets/portfolio/css-animation/loading.png",
    webLink: "https://signal-fish.gitee.io/loading/",
    sourceLink: "https://github.com/signal-fish/loading",
  },
  {
    id: 11,
    title: "tours",
    category: "react",
    image: "assets/portfolio/react/tours.png",
    webLink: "https://signal-fish.gitee.io/tours/",
    sourceLink: "https://github.com/signal-fish/tours",
  },
  {
    id: 12,
    title: "accordion",
    category: "react",
    image: "assets/portfolio/react/accordion.png",
    webLink: "https://signal-fish.gitee.io/accordion/",
    sourceLink: "https://github.com/signal-fish/accordion",
  },
  {
    id: 13,
    title: "menu",
    category: "react",
    image: "assets/portfolio/react/menu.png",
    webLink: "https://signal-fish.gitee.io/menu/",
    sourceLink: "https://github.com/signal-fish/menu",
  },
  {
    id: 14,
    title: "tabs",
    category: "react",
    image: "assets/portfolio/react/tabs.png",
    webLink: "https://signal-fish.gitee.io/tabs/",
    sourceLink: "https://github.com/signal-fish/tabs",
  },
  {
    id: 15,
    title: "slider",
    category: "react",
    image: "assets/portfolio/react/slider.png",
    webLink: "https://signal-fish.gitee.io/slider/",
    sourceLink: "https://github.com/signal-fish/slider",
  },
  {
    id: 16,
    title: "shopping list",
    category: "react",
    image: "assets/portfolio/react/shopping-list.png",
    webLink: "https://signal-fish.gitee.io/shopping-list/",
    sourceLink: "https://github.com/signal-fish/shopping-list",
  },
  {
    id: 17,
    title: "sidebar and modal",
    category: "react",
    image: "assets/portfolio/react/sidebar-modal.png",
    webLink: "https://signal-fish.gitee.io/sidebar-modal/",
    sourceLink: "https://github.com/signal-fish/sidebar-modal",
  },
  {
    id: 18,
    title: "navbar",
    category: "react",
    image: "assets/portfolio/react/navbar.png",
    webLink: "https://signal-fish.gitee.io/navbar/",
    sourceLink: "https://github.com/signal-fish/navbar",
  },
  {
    id: 19,
    title: "stripe",
    category: "react",
    image: "assets/portfolio/react/stripe.png",
    webLink: "https://signal-fish.gitee.io/stripe/",
    sourceLink: "https://github.com/signal-fish/stripe",
  },
  {
    id: 20,
    title: "cart",
    category: "react",
    image: "assets/portfolio/react/cart.png",
    webLink: "https://signal-fish.gitee.io/cart/",
    sourceLink: "https://github.com/signal-fish/cart",
  },
  {
    id: 21,
    title: "cocktails",
    category: "react",
    image: "assets/portfolio/react/cocktails.png",
    webLink: "https://signal-fish.gitee.io/cocktails/",
    sourceLink: "https://github.com/signal-fish/cocktails",
  },
  {
    id: 22,
    title: "markdown preview",
    category: "react",
    image: "assets/portfolio/react/markdown-preview.png",
    webLink: "https://signal-fish.gitee.io/markdown-preview/",
    sourceLink: "https://github.com/signal-fish/markdown-preview",
  },
  {
    id: 23,
    title: "dark mode",
    category: "react",
    image: "assets/portfolio/react/dark-mode.png",
    webLink: "https://signal-fish.gitee.io/dark-mode/",
    sourceLink: "https://github.com/signal-fish/dark-mode",
  },
];

export default portfolios;
