import {
  FaGithub,
  FaLinkedin,
  FaHtml5,
  FaReact,
  FaNodeJs,
  FaGitAlt,
  FaPython,
  FaUbuntu,
} from "react-icons/fa";
import { IoLogoCss3, IoLogoJavascript } from "react-icons/io";
import {
  SiMongodb,
  SiExpress,
  SiWebpack,
  SiMaterialui,
  SiAntdesign,
  SiJquery,
  SiRedux,
} from "react-icons/si";
import { BsFillBootstrapFill, BsFillPersonFill } from "react-icons/bs";

export const socials = [
  {
    id: 1,
    name: "github",
    icon: <FaGithub />,
    link: "https://github.com/signal-fish",
    lightColor: "#000",
    darkColor: "#7979f8",
  },
  {
    id: 2,
    name: "website",
    icon: <BsFillPersonFill />,
    link: "https://signal-fish.gitee.io/",
    lightColor: "#000",
    darkColor: "#7979f8",
  },
  {
    id: 3,
    name: "linkedIn",
    icon: <FaLinkedin />,
    link: "https://www.linkedin.com/in/signal-fish-552aaa211/",
    lightColor: "#000",
    darkColor: "#7979f8",
  },
];

export const skills = [
  {
    id: 1,
    name: "HTML5",
    icon: <FaHtml5 />,
    level: "80%",
    lightColor: "orange",
    darkColor: "yellowgreen",
  },
  {
    id: 2,
    name: "CSS3",
    icon: <IoLogoCss3 />,
    level: "70%",
    lightColor: "#0277BD",
    darkColor: "#039BE5",
  },
  {
    id: 3,
    name: "JavaScript",
    icon: <IoLogoJavascript />,
    level: "70%",
    lightColor: "#000",
    darkColor: "yellow",
  },
  {
    id: 4,
    name: "React",
    icon: <FaReact />,
    level: "75%",
    lightColor: "blue",
    darkColor: "lightskyblue",
  },
  {
    id: 5,
    name: "Redux",
    icon: <SiRedux />,
    level: "50%",
    lightColor: "blue",
    darkColor: "lightskyblue",
  },
  {
    id: 5,
    name: "Bootstrap",
    icon: <BsFillBootstrapFill />,
    level: "60%",
    lightColor: "blue",
    darkColor: "rgb(84, 84, 247)",
  },
  {
    id: 6,
    name: "Material UI",
    icon: <SiMaterialui />,
    level: "70%",
    lightColor: "#0288d1",
    darkColor: "#29b6f6",
  },
  {
    id: 7,
    name: "Ant Design",
    icon: <SiAntdesign />,
    level: "65%",
    lightColor: "#0288d1",
    darkColor: "#29b6f6",
  },
  {
    id: 9,
    name: "jQuery",
    icon: <SiJquery />,
    level: "70%",
    lightColor: "#0288d1",
    darkColor: "#29b6f6",
  },
  {
    id: 8,
    name: "Git",
    icon: <FaGitAlt />,
    level: "70%",
    lightColor: "green",
    darkColor: "orange",
  },
  {
    id: 9,
    name: "Webpack",
    icon: <SiWebpack />,
    level: "65%",
    lightColor: "#7979f8",
    darkColor: "lightblue",
  },

  {
    id: 10,
    name: "Python",
    icon: <FaPython />,
    level: "60%",
    lightColor: "#420420",
    darkColor: "#8cc84b",
  },
  {
    id: 11,
    name: "Ubuntu",
    icon: <FaUbuntu />,
    level: "50%",
    lightColor: "#420420",
    darkColor: "#8cc84b",
  },
  {
    id: 12,
    name: "NodeJS",
    icon: <FaNodeJs />,
    level: "45%",
    lightColor: "#5e9129",
    darkColor: "#8cc84b",
  },
  {
    id: 13,
    name: "Express",
    icon: <SiExpress />,
    level: "50%",
    lightColor: "#000",
    darkColor: "#fff",
  },
  {
    id: 14,
    name: "MongoDB",
    icon: <SiMongodb />,
    level: "30%",
    lightColor: "green",
    darkColor: "#6cac48",
  },
];

export const languages = [
  {
    id: 1,
    name: "Chinese",
    icon: "assets/icons/languages/china.svg",
    level: "85%",
  },
  {
    id: 2,
    name: "English",
    icon: "assets/icons/languages/america.svg",
    level: "60%",
  },
];
