import {
  FaGithub,
  FaLinkedin,
  FaHtml5,
  FaReact,
  // FaNodeJs,
  FaGitAlt,
  // FaPython,
  FaUbuntu,
  FaFileExcel,
  FaFileWord,
  FaVuejs
} from "react-icons/fa";
import { IoLogoCss3, IoLogoJavascript } from "react-icons/io";
import {
  // SiMongodb,
  // SiExpress,
  SiWebpack,
  SiMaterialui,
  SiAntdesign,
  SiJquery,
  SiRedux,
  // SiGo,
  // SiDjango,
} from "react-icons/si";
import { BsFillBootstrapFill, BsFillPersonFill } from "react-icons/bs";

export const socials = [
  {
    id: 1,
    name: "github",
    icon: <FaGithub />,
    link: "https://github.com/signal-fish",
    lightColor: "#000",
    darkColor: "#7979f8",
  },
  {
    id: 2,
    name: "website",
    icon: <BsFillPersonFill />,
    link: "https://signal-fish.gitee.io/",
    lightColor: "#000",
    darkColor: "#7979f8",
  },
  {
    id: 3,
    name: "linkedIn",
    icon: <FaLinkedin />,
    link: "https://www.linkedin.com/in/signal-fish-552aaa211/",
    lightColor: "#000",
    darkColor: "#7979f8",
  },
];

export const skills = [
  {
    id: 1,
    name: "HTML5",
    icon: <FaHtml5 />,
    level: "80%",
    lightColor: "orange",
    darkColor: "yellowgreen",
  },
  {
    id: 2,
    name: "CSS3",
    icon: <IoLogoCss3 />,
    level: "70%",
    lightColor: "#0277BD",
    darkColor: "#039BE5",
  },
  {
    id: 3,
    name: "JavaScript",
    icon: <IoLogoJavascript />,
    level: "70%",
    lightColor: "#000",
    darkColor: "yellow",
  },
  {
    id: 4,
    name: "React",
    icon: <FaReact />,
    level: "75%",
    lightColor: "blue",
    darkColor: "lightskyblue",
  },
  {
    id: 4,
    name: "Vue",
    icon: <FaVuejs />,
    level: "65%",
    lightColor: "#42b883",
    darkColor: "#42b883",
  },
  {
    id: 5,
    name: "Redux",
    icon: <SiRedux />,
    level: "50%",
    lightColor: "blue",
    darkColor: "lightskyblue",
  },
  {
    id: "5-1",
    name: "Bootstrap",
    icon: <BsFillBootstrapFill />,
    level: "60%",
    lightColor: "blue",
    darkColor: "rgb(84, 84, 247)",
  },
  {
    id: 6,
    name: "Material UI",
    icon: <SiMaterialui />,
    level: "70%",
    lightColor: "#0288d1",
    darkColor: "#29b6f6",
  },
  {
    id: 7,
    name: "Ant Design",
    icon: <SiAntdesign />,
    level: "65%",
    lightColor: "#0288d1",
    darkColor: "#29b6f6",
  },
  {
    id: "7-1",
    name: "jQuery",
    icon: <SiJquery />,
    level: "70%",
    lightColor: "#0288d1",
    darkColor: "#29b6f6",
  },
  {
    id: 8,
    name: "Git",
    icon: <FaGitAlt />,
    level: "70%",
    lightColor: "green",
    darkColor: "orange",
  },
  {
    id: 9,
    name: "Webpack",
    icon: <SiWebpack />,
    level: "65%",
    lightColor: "#7979f8",
    darkColor: "lightblue",
  },
  // {
  //   id: 10,
  //   name: "Python",
  //   icon: <FaPython />,
  //   level: "60%",
  //   lightColor: "#420420",
  //   darkColor: "#8cc84b",
  // },
  // {
  //   id: 11,
  //   name: "Golang",
  //   icon: <SiGo style={{ fontSize: "28", marginLeft: "-6px" }} />,
  //   level: "70%",
  //   lightColor: "#000000",
  //   darkColor: "#00acd7",
  // },
  {
    id: 12,
    name: "Ubuntu",
    icon: <FaUbuntu />,
    level: "50%",
    lightColor: "#420420",
    darkColor: "#8cc84b",
  },
  {
    id: 12-1,
    name: "Word",
    icon: <FaFileWord />,
    level: "60%",
    lightColor: "#2B579A",
    darkColor: "#2B579A",
  },
  {
    id: 12-2,
    name: "Excel",
    icon: <FaFileExcel />,
    level: "50%",
    lightColor: "#217346",
    darkColor: "#217346",
  },
  // {
  //   id: 13,
  //   name: "NodeJS",
  //   icon: <FaNodeJs />,
  //   level: "45%",
  //   lightColor: "#5e9129",
  //   darkColor: "#8cc84b",
  // },
  // {
  //   id: 14,
  //   name: "Express",
  //   icon: <SiExpress />,
  //   level: "50%",
  //   lightColor: "#000",
  //   darkColor: "#fff",
  // },
  // {
  //   id: 15,
  //   name: "MongoDB",
  //   icon: <SiMongodb />,
  //   level: "30%",
  //   lightColor: "green",
  //   darkColor: "#6cac48",
  // },
  // {
  //   id: 16,
  //   name: "Django",
  //   icon: <SiDjango />,
  //   level: "30%",
  //   lightColor: "#000000",
  //   darkColor: "#ffffff",
  // },
];

export const languages = [
  {
    id: 1,
    name: "Chinese",
    icon: "assets/icons/languages/china.svg",
    level: "85%",
  },
  {
    id: 2,
    name: "English",
    icon: "assets/icons/languages/america.svg",
    level: "70%",
  },
];
